name: fenix_dbt
version: '1.0.0'
config-version: 2
profile: fenix
model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fenix_dbt:
    silver:
      +materialized: view
    gold:
      +materialized: table

vars:
  warehouse_path: "lakehouse"
